//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YoutubeAPI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YoutubeAPI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot;&quot;http://www.w3.org/TR/html4/loose.dtd&quot;&gt;
        ///&lt;!Create date: 2015.04.16 09:51 PM&gt;
        ///&lt;html lang=&quot;en&quot;&gt; 
        ///&lt;head&gt;
        ///	&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=Edge&quot; /&gt;
        ///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt; 
        ///    &lt;title&gt;Video in channel&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body
        ///        {{
        ///            font-family: Segoe UI;
        ///        }}
        ///
        ///        .vidItem {{
        ///            display:inline-block;
        ///            widt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string body_template {
            get {
                return ResourceManager.GetString("body_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///	&lt;td&gt;&lt;img src=&quot;{5}&quot; /&gt;&lt;/td&gt;
        ///	&lt;td&gt;&lt;a href=&quot;https://www.youtube.com/channel/{4}/videos&quot; target=&quot;_blank&quot;&gt;&lt;b&gt;{0}&lt;/b&gt;&lt;/a&gt;&lt;/td&gt;
        ///	&lt;td&gt;{1:n0}&lt;/td&gt;
        ///	&lt;td&gt;{2:n0}&lt;/td&gt;
        ///	&lt;td&gt;{3:n0}&lt;/td&gt;
        ///	&lt;td&gt;{4}&lt;/td&gt;
        ///&lt;/tr&gt;.
        /// </summary>
        internal static string channel_template {
            get {
                return ResourceManager.GetString("channel_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///        &lt;title&gt;My Trans&lt;/title&gt;
        ///
        ///        &lt;script src=&quot;https://code.jquery.com/jquery-2.2.0.min.js&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;
        ///        &lt;script src=&quot;https://cdn.datatables.net/1.10.10/js/jquery.dataTables.min.js&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;
        ///        &lt;link href=&quot;https://cdn.datatables.net/1.10.10/css/jquery.dataTables.min.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot;&gt;
        ///
        ///        &lt;style type=&quot;text/css&quot;&gt;
        ///            body {{
        ///                fo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string channelwrapper_template {
            get {
                return ResourceManager.GetString("channelwrapper_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         &lt;li class=&quot;vidItem&quot;&gt;
        ///            &lt;img src=&quot;{0}&quot;&gt;
        ///            &lt;a href=&quot;https://www.youtube.com/watch?v={1}&quot; class=&quot;title&quot; target=&quot;_blank&quot;&gt;{2}&lt;/a&gt;
        ///            &lt;span class=&quot;view&quot;&gt;{3} views - {4}&lt;/span&gt;
        ///        &lt;/li&gt;.
        /// </summary>
        internal static string item_template {
            get {
                return ResourceManager.GetString("item_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STqIKwWZnTI,Ngza3XCB4wU,NIJfKuTuNIk,RAfEaaaDdbI,nwb7FknFWjA,h6oaW7AkU3Q,y84BWL18VlQ,D57HxN2IceY,IStY-SnSxo8,725vjOxeHHk,eKQiRAVxaIY,IzxmKD2Gqcw,u_EcjtkuDyg,Fwc6t9J7G0M,HKExaB_D2x4,wOZRbc_nwyA,Zp_PhnYVxnc,tjx9abHUbOY,AuG33AWkACo,nBbNz6-0IbE,n0SFMUfS3XM,3QSlqcEoJg0,DYjHbfDGXeU,nQuasjt0Kgs,z88guwEZQ0k,Z0-op82TjQA,bLHl_fYbBaE,4r4Rj6cmItE,9BNs_6QIwlA,-K6fhhnO9l8,v6QlJDz5Fzo,dDevMzBHne8,0dvGhdGxWSY,QDT07mlp_Ic,YxULTBM9SXE,HhuYNVO4nDw,jcbRJ2DdCNc,7hUsEIehYCg,ccxWMDvoyDw,HGyfb_60bwg,IbyVUKZlSYE,bnCVY2qLkNs,DamDVWq2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vidlist {
            get {
                return ResourceManager.GetString("vidlist", resourceCulture);
            }
        }
    }
}
